[features]
seeds = false
skip-lint = false
[programs.localnet]
tictac = "7x934apzxUTuS55Jb6EJ3kb3ub5BeLfeTJVZ2yKNZYrh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mort1b/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
